# Generated by Django 3.0.3 on 2020-02-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_auto_20200203_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='visited_rooms',
            field=models.ManyToManyField(to='adventure.Room'),
        ),
    ]
