# Generated by Django 3.0.3 on 2020-02-05 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0006_auto_20200205_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='items',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='adventure.Item'),
        ),
    ]
