# Generated by Django 3.0.3 on 2020-02-05 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0007_auto_20200205_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='items_carrying',
        ),
        migrations.RemoveField(
            model_name='room',
            name='items',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
