# Generated by Django 3.0.3 on 2020-02-05 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0012_auto_20200204_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='room',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='adventure.Room'),
        ),
    ]
