# Generated by Django 3.0.3 on 2020-02-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0017_auto_20200205_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='start',
            field=models.BooleanField(default=False),
        ),
    ]
