# Generated by Django 3.0.3 on 2020-02-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0019_auto_20200205_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='glasses_color',
            field=models.CharField(default='#FFFFFF', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='glasses_style',
            field=models.CharField(default='Square', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='hoodie_color',
            field=models.CharField(default='gray', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='pants_color',
            field=models.CharField(default='darkblue', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='pupil_color',
            field=models.CharField(default='#634e34', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='shoe_color',
            field=models.CharField(default='white', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='skin_tone',
            field=models.CharField(default='#e0ac69', max_length=50),
        ),
    ]
