# Generated by Django 3.0.3 on 2020-02-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0020_auto_20200206_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='has_glasses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='has_hat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='has_headphones',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='has_sunglasses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='hat_color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='hatband_color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='headphone_color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='lens_color',
            field=models.CharField(default='', max_length=50),
        ),
    ]
