# Generated by Django 3.0.3 on 2020-02-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0021_auto_20200206_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='headphone_color_2',
            field=models.CharField(default='', max_length=50),
        ),
    ]
